// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: permissions/params.proto

package types

import (
	fmt "fmt"
	github_com_reapchain_cosmos_sdk_types "github.com/reapchain/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the module.
type Params struct {
	WhitelistEnabled                          bool                                    `protobuf:"varint,1,opt,name=whitelist_enabled,json=whitelistEnabled,proto3" json:"whitelist_enabled,omitempty" yaml:"whitelist_enabled"`
	ForcedUnbondingTime                       string                                  `protobuf:"bytes,2,opt,name=forced_unbonding_time,json=forcedUnbondingTime,proto3" json:"forced_unbonding_time,omitempty" yaml:"forced_unbonding_time"`
	GovernanceMinimumInitialDepositEnabled    bool                                    `protobuf:"varint,3,opt,name=governance_minimum_initial_deposit_enabled,json=governanceMinimumInitialDepositEnabled,proto3" json:"governance_minimum_initial_deposit_enabled,omitempty" yaml:"governance_minimum_initial_deposit_enabled"`
	GovernanceMinimumInitialDepositPercentage github_com_reapchain_cosmos_sdk_types.Dec `protobuf:"bytes,4,opt,name=governance_minimum_initial_deposit_percentage,json=governanceMinimumInitialDepositPercentage,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"governance_minimum_initial_deposit_percentage,omitempty" yaml:"governance_minimum_initial_deposit_percentage"`
}

func (m *Params) Reset()      { *m = Params{} }
func (*Params) ProtoMessage() {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cf04d83fe451c6a, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetWhitelistEnabled() bool {
	if m != nil {
		return m.WhitelistEnabled
	}
	return false
}

func (m *Params) GetForcedUnbondingTime() string {
	if m != nil {
		return m.ForcedUnbondingTime
	}
	return ""
}

func (m *Params) GetGovernanceMinimumInitialDepositEnabled() bool {
	if m != nil {
		return m.GovernanceMinimumInitialDepositEnabled
	}
	return false
}

func init() {
	proto.RegisterType((*Params)(nil), "reapchain.permissions.v1.Params")
}

func init() { proto.RegisterFile("permissions/params.proto", fileDescriptor_7cf04d83fe451c6a) }

var fileDescriptor_7cf04d83fe451c6a = []byte{
	// 427 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0xbf, 0x8b, 0xd4, 0x40,
	0x14, 0xc7, 0x77, 0xce, 0xf3, 0xd0, 0x60, 0xa1, 0xab, 0x42, 0x50, 0xc9, 0x2c, 0x29, 0x8e, 0x55,
	0xbc, 0x84, 0xc3, 0x13, 0xe5, 0xec, 0xd6, 0xb3, 0xb0, 0x10, 0x8f, 0x45, 0x1b, 0x9b, 0x30, 0x49,
	0x9e, 0xc9, 0xc3, 0xcc, 0x0f, 0x32, 0xb3, 0x7b, 0x6e, 0xe7, 0x9f, 0x60, 0x69, 0x23, 0xf8, 0xa7,
	0x58, 0x6a, 0x77, 0xa5, 0x58, 0x04, 0xd9, 0xed, 0x52, 0xfa, 0x17, 0x88, 0x19, 0x6f, 0x37, 0xcb,
	0x1d, 0x98, 0xab, 0x32, 0x7c, 0xf3, 0x99, 0xf7, 0xde, 0x67, 0xe0, 0x39, 0xae, 0x82, 0x92, 0xa3,
	0xd6, 0x28, 0x85, 0x0e, 0x15, 0x2b, 0x19, 0xd7, 0x81, 0x2a, 0xa5, 0x91, 0x7d, 0xb7, 0x04, 0xa6,
	0x92, 0x9c, 0xa1, 0x08, 0x5a, 0x4c, 0x30, 0xdd, 0xbd, 0x75, 0x23, 0x93, 0x99, 0x6c, 0xa0, 0xf0,
	0xef, 0xc9, 0xf2, 0xfe, 0xd7, 0x8b, 0xce, 0xd6, 0x61, 0x53, 0xa0, 0x9f, 0x3b, 0xd7, 0x8e, 0x72,
	0x34, 0x50, 0xa0, 0x36, 0x11, 0x08, 0x16, 0x17, 0x90, 0xba, 0x64, 0x40, 0x86, 0x97, 0x46, 0x4f,
	0xea, 0x8a, 0xde, 0x3e, 0xf5, 0xf3, 0xbe, 0xe4, 0x68, 0x80, 0x2b, 0x33, 0xfb, 0x5d, 0x51, 0x77,
	0xc6, 0x78, 0xb1, 0xef, 0x9f, 0x82, 0xfc, 0xf1, 0xd5, 0x65, 0xf6, 0xcc, 0x46, 0xfd, 0x23, 0xe7,
	0xe6, 0x5b, 0x59, 0x26, 0x90, 0x46, 0x13, 0x11, 0x4b, 0x91, 0xa2, 0xc8, 0x22, 0x83, 0x1c, 0xdc,
	0x8d, 0x01, 0x19, 0x5e, 0x1e, 0x3d, 0xad, 0x2b, 0x4a, 0xcf, 0x04, 0xd6, 0x3a, 0xde, 0xb1, 0x1d,
	0xcf, 0x04, 0xfd, 0xf1, 0x75, 0x9b, 0xbf, 0x3e, 0x89, 0x5f, 0x21, 0x87, 0xfe, 0x77, 0xe2, 0xdc,
	0xcb, 0xe4, 0x14, 0x4a, 0xc1, 0x44, 0x02, 0x11, 0x47, 0x81, 0x7c, 0xc2, 0x23, 0x14, 0x68, 0x90,
	0x15, 0x51, 0x0a, 0x4a, 0x6a, 0x5c, 0xc9, 0x5f, 0x68, 0xe4, 0x79, 0x5d, 0xd1, 0xbd, 0xee, 0xb7,
	0xd6, 0x66, 0xdc, 0xb5, 0x33, 0x76, 0xbf, 0xed, 0x8f, 0xb7, 0x57, 0xf0, 0x0b, 0xcb, 0x3e, 0xb7,
	0xe8, 0x81, 0x25, 0x4f, 0x1e, 0xf1, 0xc3, 0x86, 0xb3, 0xd3, 0xa1, 0xae, 0x82, 0x32, 0x01, 0x61,
	0x58, 0x06, 0xee, 0xe6, 0x80, 0x0c, 0xaf, 0x8c, 0x3e, 0x93, 0x9f, 0x15, 0xdd, 0xce, 0xd0, 0xe4,
	0x93, 0x38, 0x48, 0x24, 0x0f, 0x13, 0xa9, 0xb9, 0xd4, 0xff, 0x3e, 0x3b, 0x3a, 0x7d, 0x17, 0x9a,
	0x99, 0x02, 0x1d, 0x1c, 0x40, 0x52, 0x57, 0xf4, 0xd1, 0xb9, 0x7a, 0xac, 0xc9, 0xef, 0x75, 0x96,
	0x5f, 0x15, 0xf0, 0xc7, 0x77, 0xff, 0xe3, 0x7f, 0xb8, 0x64, 0xf7, 0x37, 0x3f, 0x7d, 0xa1, 0xbd,
	0xd1, 0xcb, 0x6f, 0x73, 0x8f, 0x1c, 0xcf, 0x3d, 0xf2, 0x6b, 0xee, 0x91, 0x8f, 0x0b, 0xaf, 0x77,
	0xbc, 0xf0, 0x7a, 0x3f, 0x16, 0x5e, 0xef, 0xcd, 0xc3, 0x96, 0xe5, 0x72, 0x2f, 0x5a, 0xa7, 0xe9,
	0xe3, 0xf0, 0x7d, 0xd8, 0x5e, 0xa5, 0x46, 0x3c, 0xde, 0x6a, 0x56, 0xe3, 0xc1, 0x9f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xb8, 0xa5, 0x63, 0x2d, 0x66, 0x03, 0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if !m.GovernanceMinimumInitialDepositPercentage.IsNil() {
		{
			size := m.GovernanceMinimumInitialDepositPercentage.Size()
			i -= size
			if _, err := m.GovernanceMinimumInitialDepositPercentage.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
			i = encodeVarintParams(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if m.GovernanceMinimumInitialDepositEnabled {
		i--
		if m.GovernanceMinimumInitialDepositEnabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x18
	}
	if len(m.ForcedUnbondingTime) > 0 {
		i -= len(m.ForcedUnbondingTime)
		copy(dAtA[i:], m.ForcedUnbondingTime)
		i = encodeVarintParams(dAtA, i, uint64(len(m.ForcedUnbondingTime)))
		i--
		dAtA[i] = 0x12
	}
	if m.WhitelistEnabled {
		i--
		if m.WhitelistEnabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.WhitelistEnabled {
		n += 2
	}
	l = len(m.ForcedUnbondingTime)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	if m.GovernanceMinimumInitialDepositEnabled {
		n += 2
	}
	if !m.GovernanceMinimumInitialDepositPercentage.IsNil() {
		l = m.GovernanceMinimumInitialDepositPercentage.Size()
		n += 1 + l + sovParams(uint64(l))
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field WhitelistEnabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.WhitelistEnabled = bool(v != 0)
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ForcedUnbondingTime", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ForcedUnbondingTime = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field GovernanceMinimumInitialDepositEnabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.GovernanceMinimumInitialDepositEnabled = bool(v != 0)
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GovernanceMinimumInitialDepositPercentage", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var v github_com_reapchain_cosmos_sdk_types.Dec
			m.GovernanceMinimumInitialDepositPercentage = v
			if err := m.GovernanceMinimumInitialDepositPercentage.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
